### PR TITLE
Diagnostics addition to sourcetracker

### PR DESCRIPTION
**Pull request by andy6a**
Please test this code and let me know what you would like to do with it, may not fully follow code standards so let me know what you think

### CODE REVIEW

**Review by cherman2 — COMMENTED** [review]
This LGTM. I have made a couple of inline changes. They aren't anything big. I am going to pull this down tomorrow to test and I will get back to you then!

**Comment by andy6a** [comment]
Those changes look great I didn't have it in code format because I was having an error with diagnostics that I was just trying to solve quickly so that looks great to me!

**Comment by cherman2** [comment]
Hi @andy6a, 
Could you take a look at the flake8 errors (By clicking on the failed check) and fix those errors that are causing that check to fail?

**Comment by wasade** [comment]
Not sure if relevant to this PR, but please note that refactoring to reduce dependence on dense matrices, and greatly reduce resident memory requirements, is part of this [branch](https://github.com/biocore/sourcetracker2/tree/be_sparse). It would be pleasant to figure out how we can get the useful changes merged into master

**Comment by andy6a** [comment]
Man it is really picky about line numbers. That said I got it done, sorry that took so long.

**Pull request merged**
