### PR TITLE
Update to Python 3.8 with Depreciated code fix

### PR DESCRIPTION
**Pull request by andy6a**
I updated the main readme with the procedure that I got to work using python 3.8 which was requested. An error occurred on line 778 of the sourcetracker file as the code was depreciated so I updated that too. If there is still an issue with the update the next pull request will likely patch it.

### CODE REVIEW

**Comment by cherman2** [comment]
@andy6a, 
This looks good to me! I am gonna try to get some automatic tests set up so that github checks linting (And maybe runs unit tests).  Then I will pull down this PR and test it locally! Should get back to you by EOD!

**Comment by wasade** [comment]
I'm not sure if this is relevant, but we did a fair amount of work to address issues in ST2 a few months back. We maintained it as a separate fork as at the time ST2 was not maintained. Please see https://github.com/biocore/sourcetracker2/tree/be_sparse

**Review by cherman2 — COMMENTED** [review]
Hi @andy6a, 

This is a great start and thanks for your patience as I reviewed this! 
I have 2 comments on this PR
1) When I pulled this down locally to test it locally and I got a couple of pytest errors. Did you also have errors when you ran pytest locally? 
2) It seems like you moved biom-format from the conda create command to a pip install because of conflicts. Ideally for the qiime2 plugin and for easy of distribution of the software, we want to have everything installable via a conda command. I tried messing around with pinning packages to try to resolve the conflicts and I was not able to find a way to resolve the conflicts. Hopefully we can find away to keep biom-format in the conda create command. If you need help wrestling with the conda conflicts, I could connect you with one of our software engineers who might have more insight than I have. 

Also, I noticed that this is on your master branch. Personally, I like to develop on a separate "development" branch, and  keep my master branch of my forked repo clean. This is helpful in case things go wrong in your development branch and you need a clean start or if you need to create a new PR while another PR is in review. This probably isn't worth fixing for this PR but may be helpful for future PRs!

**Comment by andy6a** [comment]
Hey @cherman2 

Yes I have errors when I pytest locally. In fact it was a recurring issue. First, one of the errors is triggered when there are no sinks and we actually need to look at that section because it simply does not work properly regardless of the if statement. Second, a noticeable issue is triggered by the ordering and specificity of the inputs in certain places for the pytest input. Thirdly, in the exceptions to the written blocks used for testing, whenever it requires multiple lines due to code format at 80 characters, it treats them as separate lines thus triggering errors. I don't know how you want to approach the last one, but the second is fixable pretty easily and the first is something I have not approached as I didn't want to mess with the code more than I needed to. (Side note: The actual program works fine without the first issue being solved so it actually wasn't a problem. Solution might be to just throw an error if there are no sinks.)
I should also be clear by saying that I do not have an issue with most of the errors as they are mostly in testing format but first time I ran it I got 42 testing errors so there is that.

As to number 2 I will be as blunt as possible. I need software engineers and have no solution for this issue in any python past 3.6.

As for your final comment that is good to know, given this was small I figured it did not matter but I will adjust in the future.

**Comment by cherman2** [comment]
@andy6a, 
All that makes sense to me! We definitely can address all those errors after we merge this PR.

I will connect you with one of our software engineers via email!

**Review by cherman2 — APPROVED** [review]

**Comment by cherman2** [comment]
LGTM! Thanks @andy6a

**Pull request merged**
